# Generated by Django 3.0.5 on 2020-04-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myreservation',
            old_name='use',
            new_name='user',
        ),
    ]
