# Generated by Django 3.0.5 on 2020-04-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_accepted',
            name='reser_status',
            field=models.CharField(choices=[('Accepted', 'accepted'), ('Rejected', 'rejected'), ('Pending', 'pending'), ('Cancel', 'cancel')], max_length=8),
        ),
    ]
