# Generated by Django 3.0.5 on 2020-04-28 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20200428_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_accepted',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.myreservation'),
        ),
    ]
