# Generated by Django 3.0.5 on 2020-04-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20200428_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='myreservation',
            name='reservation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
