# Generated by Django 3.0.5 on 2020-04-26 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_address', models.CharField(max_length=200)),
                ('restaurant_name', models.CharField(max_length=50)),
                ('seller_phone', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to='restaurant_image')),
                ('restaurant_status', models.CharField(choices=[('OP', 'open'), ('CL', 'close')], default='OP', max_length=2)),
                ('own_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, upload_to='menu_image')),
                ('menu_price', models.FloatField()),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webpage.restaurant_type'),
        ),
    ]
